### ISSUE TITLE
Warp Route UI Token selection should be greyed out instead of not existent

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#2514] opened 2023-07-11 17:34 UTC
On the warp template UI, when picking a particular set of chains, the token lists gets filtered by which tokens can actually support the selected origin/destination chains. Instead, the list should grey out tokens are not selectable with a hover tooltip that says why a token cannot be selected

**Comment by ashu26jha** [comment] 2023-07-17 05:51
Hey @nambrot  I would be happy to work on it! 

> why a token cannot be selected

I am struggling with what reason should I give if the token can't selected (grayed out ones). Do we like have to go for a generic message?

**Comment by nambrot** [comment] 2023-07-17 13:04
The reason is that the warp routes configured on the instance do not support sending the token from the selected origin to the destination, that is sufficient. At some point, we'll probably want the UI or explorer to show a visualization of supported routes, but that's more complicated

**Comment by jmrossy** [comment] 2023-07-18 13:31
Dupe of https://github.com/hyperlane-xyz/hyperlane-warp-ui-template/issues/33 which has more detailed info

**Closed by jmrossy** 2023-07-18 13:31 UTC
Labels: good first issue, warp-route, ui
