### ISSUE TITLE
Docs - ICA reference

### ISSUE THREAD

**Issue by jennifermarie** [hyperlane-xyz/hyperlane-monorepo#1220] opened 2022-11-01 20:34 UTC
Reference material for Interchain Accounts. Should cover more ground than the quickstart and offer developers a practical point of reference.

**Comment by jennifermarie** [comment] 2022-11-01 20:35
This can reuse components of hyperlane-xyz/issues/issues/179

**Comment by yorhodes** [comment] 2022-11-14 16:28
potential dupe of #1269

**Closed** 2022-11-28 15:27 UTC
