### ISSUE TITLE
Relayers should be easily configurable for a given chain deployment

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#1469] opened 2022-12-21 15:10 UTC
Similar to #1468, relayers need to be configurable. They are even harder to configure since they need configuration for each chain they support. Additionally, allowlisting support needs to be documented (and possibly expanded).

Again, when you are working on this ticket consider doing any combination of the following:

- more helpful error messages when configuration cannot be parsed or validated
- documentation for necessary configuration (both the file to give to operators + ENV vars they are supposed to set)

The goal here is to find 80/20 opportunities to make this easier, while time-bounding this to the extreme short-term to allow us to write documentation to make #1450 practical, if not perfect

**Comment by tkporter** [comment] 2022-12-21 15:21
Renamed this to not be a dupe of https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/1468

**Closed** 2023-01-17 23:29 UTC
