### ISSUE TITLE
Allow a single relayer instance to relay from multiple origin chains

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#1760] opened 2023-02-03 22:43 UTC
The investigate ticket for https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/1899

**Comment by asaj** [comment] 2023-02-23 17:49
> maybe just do it in a backwards compatible way ideally

Wdym by this?

**Comment by asaj** [comment] 2023-02-23 17:50
> We should quickly investigate if there is an easy way to run the relayer differently without incurring that overhead

What overhead?

**Comment by asaj** [comment] 2023-05-03 14:25
Dupe of omniscient relayer ticket #1899

**Closed by asaj** 2023-05-03 14:25 UTC
Labels: agent, investigate, permissionless-deployment
