### ISSUE TITLE
Sealevel: document how everything works

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-monorepo#2355] opened 2023-06-07 18:16 UTC
Atm most of the design decisions and how to run everything lives in my mind! I want to get this all down on paper including operations

**Comment by avious00** [comment] 2023-08-08 21:58
@tkporter bringing your sealevel docs issue in for the following cycle

**Comment by avious00** [comment] 2023-11-22 04:56
dupe of https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2756

**Closed by avious00** 2023-11-22 04:56 UTC
Labels: sealevel
