### ISSUE TITLE
Interchain queries

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#882] opened 2022-08-04 14:09 UTC

**Comment by yorhodes** [comment] 2022-08-04 17:09
experiments here https://github.com/yorhodes/abacus-fetch/blob/main/contracts/Fetch.sol

**Comment by asaj** [comment] 2022-09-20 21:16
Dupe of https://github.com/hyperlane-xyz/issues/issues/174

**Closed by asaj** 2022-09-20 21:16 UTC
Labels: epic
