### ISSUE TITLE
Syncing token repo is cumbersome

### ISSUE THREAD

**Issue by nambrot** [hyperlane-xyz/hyperlane-monorepo#2170] opened 2023-05-04 16:15 UTC
Syncing token changes to the monorepo via the submodule is cumbersome and annoying and the benefit of the token package being a separate package is unclear at this point.

Suggest to move it back into the monorepo to make deploying changes easier.

**Comment by asaj** [comment] 2023-05-04 16:29
Dupe of https://github.com/hyperlane-xyz/hyperlane-token/issues/68

**Comment by asaj** [comment] 2023-05-04 16:30
Glad to have you on board

**Closed** 2023-05-04 16:42 UTC
Labels: core, dx, operations
