### ISSUE TITLE
Support tokens as interchain gas payment for a unified fee on warp route transfers

### ISSUE THREAD

**Issue by yorhodes** [hyperlane-xyz/hyperlane-monorepo#3177] opened 2024-01-23 22:34 UTC
## Problem

The (EVM) IGP only supports native value payments. The (EVM) hook interface only supports native value quotes. Any warp route which does not collateralize a native asset implies two different fees associated with a transfer. This makes multihop/packet forwarding especially annoying.

## Solution

Instead of modifying the hook interface to support token quotes (CW supports this) and handling token approvals to some other IGP contract address, we could modify warp routes to deduct the IGP fee from transfers.

## Nice to Have

If the new warp routes comply with the existing IGP event interface, Relayers could simply be configured with the warp route address as the IGP and begin to service these warp routes

**Comment by avious00** [comment] 2024-03-01 04:45
@nambrot how does this fit with the other fee issues?

**Comment by nambrot** [comment] 2024-03-01 13:14
yeah, IMO dupe of https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3060 @yorhodes ?

**Comment by avious00** [comment] 2024-03-19 20:38
duplicate of https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3060 - merged content in there

**Closed by avious00** 2024-03-19 20:38 UTC
Labels: IGP, warp-route, hooks
