### ISSUE TITLE
Fallback provider is susceptible to a stuck node

### ISSUE THREAD

**Issue by mattiekat** [hyperlane-xyz/hyperlane-monorepo#2570] opened 2023-07-26 20:33 UTC
After a lot of digging for a production problem, it became clear that the fallback provider for `sepolia` is not falling back when the provider returns a valid response but the provider itself is stuck and 5+ days behind. The fallback provider should have some mechanism by which it realizes the block number is behind the rest of the pack and switches.

**Comment by mattiecnvr** [comment] 2023-07-26 20:34
https://discord.com/channels/935678348330434570/1133827653338677310

**Comment by mattiecnvr** [comment] 2023-07-26 20:42
Also worth noting that in this specific case the "stuck" node was and is progressing still, it just is getting progressively more behind.

![image](https://github.com/hyperlane-xyz/hyperlane-monorepo/assets/4187749/48897712-8529-45b4-aab0-ac24d7ca78de)

**Comment by nambrot** [comment] 2023-07-27 14:34
Did we not fix this with https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2189 or was it just not deployed?

**Comment by nambrot** [comment] 2023-07-27 14:34
cc @daniel-savu

**Comment by nambrot** [comment] 2023-07-27 22:08
@mattiecnvr can you confirm that running the latest image will not exhibit this problem?

**Comment by nambrot** [comment] 2024-03-01 18:43
@daniel-savu this still is an issue? or is it a dupe of https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3304 cc @avious00

**Comment by tkporter** [comment] 2024-03-04 11:56
I think this was created before we had *any* liveness heuristic, and the outcome of this was our current situation of "if no new block has come in X mins, consider the provider unhealthy"

And now #3304 is realizing that our current liveness heuristic is insufficient because of chains that create blocks on demand. So I'm gonna close this in favor of #3304

**Closed by tkporter** 2024-03-04 11:56 UTC
