### ISSUE TITLE
Single broken provider causes FallbackProvider to fail

### ISSUE THREAD

**Issue by asaj** [hyperlane-xyz/hyperlane-monorepo#2024] opened 2023-03-27 14:47 UTC
Non static providers occasionally ping chain ID, and when that fails, the process throws an exception

We may want to use StaticJsonRPCProvider when building our FallbackProviders

**Comment by jmrossy** [comment] 2023-04-18 11:25
Yes I agree, we should be using `StaticJsonRPCProvider` in most places

**Comment by nambrot** [comment] 2023-05-03 00:07
@jmrossy Is this basically done? You basically moved to using them by default in MP right? 

I think the only outstanding spot for this would then be for the MP construction from the gcloud secrets for this issue?

**Comment by jmrossy** [comment] 2023-05-03 12:32
@nambrot It's mostly done but I haven't confirmed if an error thrown by a sub-provider in a fallback provider does indeed cause the entire request to fail. If it does, we'd need to extend and tweak FallbackProvider.

SmartProvider handles this better so recommend we close this and defer further improvements til we use SmartProvider in the SDK by default

**Comment by jmrossy** [comment] 2023-09-13 19:31
Reopening as I'm seeing frequent errors in the warp UI stemming from flaky Sepolia RPCs. It seems that Ethers' FallbackProvider does indeed fail on a failure from any sub-provider.

Time to reconsider moving SmartProvider into the SDK

**Comment by avious00** [comment] 2023-11-30 05:48
also see https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2895 which may be caused by this underlying issue

**Closed** 2023-12-13 18:04 UTC
Labels: bug, reliability, operations
