### ISSUE TITLE
64-bit block heights

### ISSUE THREAD

**Issue by mattiecnvr** [hyperlane-xyz/hyperlane-monorepo#2610] opened 2023-08-04 16:43 UTC
Solana uses 64 bit block heights and I am pretty sure the EVM also uses 64 bit block numbers but usually they have a slow enough block rate that it has not mattered. This change would be to update the codebase anywhere we use a 32bit block height/number and use a 64 bit one.

**Comment by tkporter** [comment] 2023-08-08 10:48
Btw dupe of https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/2275 - gonna close in favor of that. Asa and I chatted about it a while back and it'll be a long time till u32 overflows so no need to do this very soon

**Closed by tkporter** 2023-08-08 10:48 UTC
